### ISSUE TITLE
redirect loop with standard configuration

### ISSUE THREAD

**Issue by jtnk** [dalehamel/okta-auth-proxy#1]
Hey @dalehamel 

Love the project, I've been working on a guide to set this up for others that want to adapt traditional single page / oldschool htaccess apps for use with OKTA.

I've managed to get the proxy running on Ruby 2.0 (w/Required packages) and I get as far as authentication, but I get stuck in an authentication loop after a valid login via OKTA. Not sure if you ran into the same issue, but I've mirrored the nginx configuration that you included, and included all required ENV variables.

Relay State:

Name ID Format: Unspecified
Response: SignedAssertion
Signature: Signed
Signature Algorithm: RSA_SHA256
Digest Algorithm: SHA256
Assertion Encryption: Unencrypted
SAML Single Logout: Disabled
authnContextClassRef: PasswordProtectedTransport
Honor Force Authentication: Yes

Debug Info:

```
I, [2016-07-23T18:35:24.922749 #8723]  INFO -- omniauth: (saml) Request phase initiated.

D, [2016-07-23T18:35:24.923760 #8723] DEBUG -- : Created AuthnRequest: 

<samlp:AuthnRequest AssertionConsumerServiceURL='https://XXXXX/auth/saml/callback?redirectUrl=/' Destination='https://domain.okta.com/app/XXXXX/exk69leqfdZbMLMNX0x7/sso/saml' ID='_XX833e8a-XXXX-XXXXX-XXXX-4c1200bdXXX2' IssueInstant='2016-07-23T18:35:24Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><saml:Issuer>http://www.okta.com/XXXXXXXXXXXXXXXX</saml:Issuer><samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'/></samlp:AuthnRequest>
```

I'd love to see the project get a little more traction, so I'm happy to document my setup after getting things working and make a few small readme updates!

**Comment by jtnk** [comment]
I think I've solved it!

Documentation coming in a PR shortly 👍

**Comment by arunjadhav16** [comment]
Am using same but am not sure what values I should use for following fields in Okta configuration.
Single Sign On URL,
Default Relay State,
Recipient URL,
Destination URL
Help on this will be great.
